cmake_minimum_required(VERSION 3.8)

set(PROJECT_VERSION_MAJOR 0)
set(PROJECT_VERSION_MINOR 1)
set(PROJECT_VERSION_PATCH 0)

set(PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")

include_directories(
    ${ROOT_PATH}/inc
)

AUX_SOURCE_DIRECTORY(${ROOT_PATH}/src/core DIR_SRCS)
AUX_SOURCE_DIRECTORY(${ROOT_PATH}/src/misc MISC_SRCS)

list(APPEND SRC
    # ${DIR_SRCS}
    ${MISC_SRCS}
)
